export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  UserService: Symbol.for('UserService'),
  UserRepository: Symbol.for('UserRepository'),
  CategoryService: Symbol.for('CategoryService'),
  CategoryRepository: Symbol.for('CategoryRepository'),
  OfferService: Symbol.for('OfferService'),
  OfferRepository: Symbol.for('OfferRepository'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  CategoryController: Symbol.for('CategoryController'),
  UserController: Symbol.for('UserController'),
  OfferController: Symbol.for('OfferController'),
  AuthService: Symbol.for('AuthService'),
  AuthExceptionFilter: Symbol.for('AuthExceptionFilter'),
  HttpExceptionFilter: Symbol.for('HttpExceptionFilter'),
  ValidationExceptionFilter: Symbol.for('ValidationExceptionFilter'),
  PathTransformer: Symbol.for('PathTransformer'),
} as const;
